[gv] 7.36 enter part lib (.... 1919)
• this now again builds every part that was ever
  built but with this wild stack underneath it
  ('ls-files' is a simple example 'show' is complex.)

• every part can now display a description

• arbitrary extra commands entered to the build script
  (for either 'all' or 'part') now get passed all
  the way into the manifest API

• the part building scripts are now all unified
  (and their parent components cleaned up) by the
  introduction of the 'partlib')

• overhauled core payload logic of triad shell script
  to be a symmetrical masterpiece of nested booleanism.
  or so we think right now. (we had gone back in to
  add logic for when the fixture dumpfile dir doesn't
  exist, and felt like we fell into a tarpit)

• just to be cute we moved the 'generate negatives'
  build script to a future vaporware path

(4 in 32.66)

diff --git a/lib/skylab/git-viz/test/vcs-adapters-/git/asset-script/for-mock-repo-1/zsh-lib/functions/part-show b/lib/skylab/git-viz/test/vcs-adapters-/git/asset-script/for-mock-repo-1/zsh-lib/functions/part-show
--- a/lib/skylab/git-viz/test/vcs-adapters-/git/asset-script/for-mock-repo-1/zsh-lib/functions/part-show
+++ b/lib/skylab/git-viz/test/vcs-adapters-/git/asset-script/for-mock-repo-1/zsh-lib/functions/part-show
@@ -1,16 +1,88 @@
 #!/usr/bin/env zsh  #just-for-syntax-highlighting
 
-serr "pretending to do 'part show'"
-
-return $gv_success
-
-typeset transient_iam transient_out transient_err
--build-negatives-inside-of-directory () {
-  transient_out=tmp.show.456456.out.txt
-  transient_err=tmp.show.456456.err.txt
-  transient_iam=tmp.show.456456.iam.txt
-  $vcs_exe show --numstat --pretty=tformat:%ai 456456 -- \
-    1>"$transient_out" 2>"$transient_err"
-  typeset exitstatus=$?
-  print "exitstatus $exitstatus" > "$transient_iam"
+part-show-description () {
+  serr "description: build dump for the 'git show' command"
 }
+
+part-show-usage () {
+  serr "usage: $($partlib_say_invocation_name) [-h]"
+}
+
+-require-partlib
+
+typeset part_func=$0 ; typeset -a rest ; rest=("$*[@]")
+
+typeset adverb asset_output_dir
+partlib-parse-adverb-and-asset-output-dir
+
+-partlib-help && return  # #debugging: comment out to propagage to API
+
+-partlib-require-asset-output-dir || return $?
+
+--each-show-command () {
+
+  typeset cd="$2" dd ; ---prepare-cd-and-dd
+
+  typeset cmd_SHA_is_intentionally_invalid
+  typeset story_cmd_s=$1 real_cmd_s ; typeset -a cmd
+  ---prepare-cmd || return $?
+
+  typeset o e es
+  ---execute-the-cmd || return $?
+
+  ---storify-output-dumpfile || return $?
+
+  $3 $o $e $es
+}
+---prepare-cd-and-dd () {
+  if [[ ! -z  $cd ]] ; then
+    cd=/$cd ; typeset dd=/..
+  fi
+}
+---prepare-cmd () {
+  if ---cmd-intentionally-refers-to-an-invalid-sha ; then
+    cmd_SHA_is_intentionally_invalid=true
+  fi
+  if [[ "$cmd_SHA_is_intentionally_invalid" == true ]] ; then
+    real_cmd_s="$story_cmd_s"
+  else
+    real_cmd_s=$( partlib-unstorify-command "$story_cmd_s" ) || return $?
+  fi
+  cmd=(${(z)real_cmd_s})
+}
+---cmd-intentionally-refers-to-an-invalid-sha () {
+  # yes on everage there is a (4.0e-06) chance this hack will fail
+  [[ "$story_cmd_s" = *\ 456456\ -- ]] && return 0
+  return 1
+}
+---execute-the-cmd () {
+  o==() ; e==()
+  loud-cd $asset_output_dir$cd || return $?
+    serr "${triad_indent}${cmd[1]} ${(j: :)cmd[2,-1]}"
+    $cmd[1] $cmd[2,-1] 1>$o 2>$e ; es=$?
+    serr "${triad_indent}(wrote above to $o and $e)"
+  loud-cd "..$dd"
+}
+---storify-output-dumpfile () {
+  if [[ "$cmd_SHA_is_intentionally_invalid" == true ]] then
+    return $gv_success
+  fi
+  if [[ ! -s $o ]] ; then
+    serr "nothing was outputted. nothing to normalize."
+    return $gv_err_no_resource
+  fi
+  typeset match mbegin mend
+  setopt extendedglob
+  if [[ $story_cmd_s = (#b)*\ ([a-f0-9]##)\ -- ]] ; then
+    $particular_vcs_dir/script/storify-date-on-first-line "$o" "$match[1]"
+  else
+    serr "failed to parse out the fake sha from '$story_cmd_s'"
+    return $gv_err_param_is_extra_white_grammatical
+  fi
+}
+
+# print "\n\npart-repo-show:(${(f)rest})\n\n" ; return 0  # #debugging
+
+troika-lookup-system-commands --each-command --each-show-command\
+  --command-white-filter-regex '^git show\b'\
+  --chdir-prefix-white-filter /derp/berp "${rest[@]}"
